### PR TITLE
Slightly optimize code and remove redundant variables

### PR DESCRIPTION
**Pull request by M-AJ**
Slightly optimize code and remove redundant variables in Type Utils, gets used rapidly in recursive scenarios

### CODE REVIEW

**Comment by kimmking** [comment]
can you add a test case for your PR？

**Comment by M-AJ** [comment]
Yes sir! Ill give it a shot when as soon as I find some time!

**Comment by wenshao** [comment]
thank you, it very good pull request!

**Comment by M-AJ** [comment]
Thanks! Couldn't create a thorough test because I was a little busy, but looks like it checks out!

**Pull request merged**
