### PR TITLE
Fix issue #578 #577 and #574

### PR DESCRIPTION
**Pull request by VictorZeng**
`FastJsonHttpMessageConverter` is apply to using Spring MVC below 4.2
`FastJsonHttpMessageConverterNew` is apply to using Spring MVC 4.2+
The `addSerializeFilter` method‘s bug has fixed

### CODE REVIEW

**Comment by wenshao** [comment]
'FastJson4HttpMessageConverter' the className is confused, it looks like fastjson 4.0 version.

**Comment by VictorZeng** [comment]
@wenshao 。。。那应该叫什么名字呀

**Comment by VictorZeng** [comment]
@wenshao `FastJsonHttpMessageConverterNew `?

**Comment by wenshao** [comment]
FastJsonHttpMessageConverter4 ?

**Pull request merged**
